// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

`timescale 1ns/1ps

module AUTOTB_TOP;
//------------------------Parameter----------------------
localparam
    TV_IN   = "iosc.hdltvin.dat",
    TV_OUT  = "iosc.hdltvout.dat",
    ERR_LOG = "err.log";
//------------------------Local signal-------------------
reg           __aesl__clock0;
reg           reset;
reg  [3:0]    ctrl;
reg  [3:0]    inSwitch;
wire [3:0]    outLeds;
reg           __aesl__reset;
reg  [3:0]    __aesl__ctrl;
reg  [3:0]    __aesl__inSwitch;
reg  [3:0]    __aesl__outLeds;
integer __aesl__err;
//------------------------Instantiation------------------
iosc iosc_inst (
    .clk      ( __aesl__clock0 ),
    .reset    ( reset ),
    .ctrl     ( ctrl ),
    .inSwitch ( inSwitch ),
    .outLeds  ( outLeds )
);
//------------------------Task and function--------------
task read_token;
    input integer fp;
    output reg [127:0] token;
    reg [7:0] c;
    reg intoken;
    reg done;
begin
    token = "";
    intoken = 0;
    done = 0;
    while (!done) begin
        c = $fgetc(fp);
        if (c == 8'hff) begin   // EOF
            done = 1;
        end
        else if (c == " " || c == "\011" || c == "\012" || c == "\015") begin   // blank
            if (intoken) begin
                done = 1;
            end
        end
        else begin      // valid character
            intoken = 1;
            token = (token << 8) | c;
        end
    end
end
endtask

task rm_quoation;
    inout reg [127:0] token;
    reg [127:0] token_temp;
    integer idx;
begin
    token_temp = token >> 8;
    token = "";
    idx = 0;    while (token_temp[7:0] != 34 && token_temp[7:0] != "") begin
        token = (token_temp[7:0] << 8*idx) | token;
        token_temp = token_temp >> 8;
        idx = idx + 1;
    end
end
endtask

//------------------------Body---------------------------
// clock signals
initial begin : gen___aesl__clock0_process
    __aesl__clock0 = 0;
    # 0.001;
    while(1) begin
      __aesl__clock0 = ~__aesl__clock0;
      # 5.0;
    end
end

// read tv in
initial begin : __aesl__read_process
    integer __aesl__fp;
    integer __aesl__ret;
    reg [127:0] __aesl__token;
    // initialize
    __aesl__err = $fopen(ERR_LOG, "w");
    if (__aesl__err == 0) begin  // failed to create file
        $display("Failed to open file \"%s\"!", ERR_LOG);
        $display("ERROR: Simulation using HLS TB failed.");
        $finish;
    end
    __aesl__fp = $fopen(TV_IN, "r");
    if (__aesl__fp == 0) begin  // failed to open file
        $display("Failed to open file \"%s\"!", TV_IN);
        $display("ERROR: Simulation using HLS TB failed.");
        $fdisplay(__aesl__err,"Failed to open file \"%s\"!", TV_IN);
        $finish;
    end
    read_token(__aesl__fp, __aesl__token);
    if (__aesl__token != "[") begin  // illegal format
        $display("Illegal tv format of file \"%s\"!", TV_IN);
        $display("ERROR: Simulation using HLS TB failed.");
        $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
        $finish;
    end
    read_token(__aesl__fp, __aesl__token);
    if (__aesl__token != "]") begin  // no data
        if (__aesl__token != "{") begin  // illegal format
            $display("Illegal tv format of file \"%s\"!", TV_IN);
            $display("ERROR: Simulation using HLS TB failed.");
            $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
            $finish;
        end
        read_token(__aesl__fp, __aesl__token);
        while (__aesl__token != "}") begin
            if ((__aesl__token[47 : 8] == "reset") && (__aesl__token[55 : 48] == 34) && (__aesl__token[7 : 0] == 34)) begin
                read_token(__aesl__fp, __aesl__token);
                if (__aesl__token != ":") begin  // illegal format
                    $display("Illegal tv format of file \"%s\"!", TV_IN);
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
                    $finish;
                end
                read_token(__aesl__fp, __aesl__token);
                rm_quoation(__aesl__token);
                __aesl__ret = $sscanf(__aesl__token, "%b", reset);
                if (__aesl__ret != 1) begin
                    $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Failed to parse token!");
                    $finish;
                end
            end
            else if ((__aesl__token[39 : 8] == "ctrl") && (__aesl__token[47 : 40] == 34) && (__aesl__token[7 : 0] == 34)) begin
                read_token(__aesl__fp, __aesl__token);
                if (__aesl__token != ":") begin  // illegal format
                    $display("Illegal tv format of file \"%s\"!", TV_IN);
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
                    $finish;
                end
                read_token(__aesl__fp, __aesl__token);
                rm_quoation(__aesl__token);
                __aesl__ret = $sscanf(__aesl__token, "%b", ctrl);
                if (__aesl__ret != 1) begin
                    $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Failed to parse token!");
                    $finish;
                end
            end
            else if ((__aesl__token[71 : 8] == "inSwitch") && (__aesl__token[79 : 72] == 34) && (__aesl__token[7 : 0] == 34)) begin
                read_token(__aesl__fp, __aesl__token);
                if (__aesl__token != ":") begin  // illegal format
                    $display("Illegal tv format of file \"%s\"!", TV_IN);
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
                    $finish;
                end
                read_token(__aesl__fp, __aesl__token);
                rm_quoation(__aesl__token);
                __aesl__ret = $sscanf(__aesl__token, "%b", inSwitch);
                if (__aesl__ret != 1) begin
                    $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Failed to parse token!");
                    $finish;
                end
            end
            else begin  // unknown token
                $display("Unknown token \"%s\" in file \"%s\"!", __aesl__token, TV_IN);
                $display("ERROR: Simulation using HLS TB failed.");
                $fdisplay(__aesl__err,"Unknown token \"%s\" in file \"%s\"!", __aesl__token, TV_IN);
                $finish;
            end
            read_token(__aesl__fp, __aesl__token);  // skip ","
            if (__aesl__token == ",") begin
                read_token(__aesl__fp, __aesl__token);
            end
            else if (__aesl__token != "}") begin
                $display("Illegal tv format of file \"%s\"!", TV_IN);
                $display("ERROR: Simulation using HLS TB failed.");
                $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
                $finish;
            end
        end
    end
    // drive input
    __aesl__ret = $rewind(__aesl__fp);
    @(posedge __aesl__clock0);
    read_token(__aesl__fp, __aesl__token);
    if (__aesl__token != "[") begin  // illegal format
        $display("Illegal tv format of file \"%s\"!", TV_IN);
        $display("ERROR: Simulation using HLS TB failed.");
        $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
        $finish;
    end
    read_token(__aesl__fp, __aesl__token);
    while (__aesl__token != "]" && __aesl__token != "") begin
        if (__aesl__token != "{") begin  // illegal format
            $display("Illegal tv format of file \"%s\"!", TV_IN);
            $display("ERROR: Simulation using HLS TB failed.");
            $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
            $finish;
        end
        read_token(__aesl__fp, __aesl__token);
        while (__aesl__token != "}") begin
            if ((__aesl__token[47 : 8] == "reset") && (__aesl__token[55 : 48] == 34) && (__aesl__token[7 : 0] == 34)) begin
                read_token(__aesl__fp, __aesl__token);
                if (__aesl__token != ":") begin  // illegal format
                    $display("Illegal tv format of file \"%s\"!", TV_IN);
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
                    $finish;
                end
                read_token(__aesl__fp, __aesl__token);
                rm_quoation(__aesl__token);
                __aesl__ret = $sscanf(__aesl__token, "%b", __aesl__reset);
                if (__aesl__ret != 1) begin
                    $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Failed to parse token!");
                    $finish;
                end
                reset <= __aesl__reset;
            end
            else if ((__aesl__token[39 : 8] == "ctrl") && (__aesl__token[47 : 40] == 34) && (__aesl__token[7 : 0] == 34)) begin
                read_token(__aesl__fp, __aesl__token);
                if (__aesl__token != ":") begin  // illegal format
                    $display("Illegal tv format of file \"%s\"!", TV_IN);
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
                    $finish;
                end
                read_token(__aesl__fp, __aesl__token);
                rm_quoation(__aesl__token);
                __aesl__ret = $sscanf(__aesl__token, "%b", __aesl__ctrl);
                if (__aesl__ret != 1) begin
                    $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Failed to parse token!");
                    $finish;
                end
                ctrl <= __aesl__ctrl;
            end
            else if ((__aesl__token[71 : 8] == "inSwitch") && (__aesl__token[79 : 72] == 34) && (__aesl__token[7 : 0] == 34)) begin
                read_token(__aesl__fp, __aesl__token);
                if (__aesl__token != ":") begin  // illegal format
                    $display("Illegal tv format of file \"%s\"!", TV_IN);
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
                    $finish;
                end
                read_token(__aesl__fp, __aesl__token);
                rm_quoation(__aesl__token);
                __aesl__ret = $sscanf(__aesl__token, "%b", __aesl__inSwitch);
                if (__aesl__ret != 1) begin
                    $display("Failed to parse token!");
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err,"Failed to parse token!");
                    $finish;
                end
                inSwitch <= __aesl__inSwitch;
            end
            else begin  // unknown token
                $display("Unknown token \"%s\" in file \"%s\"!", __aesl__token, TV_IN);
                $display("ERROR: Simulation using HLS TB failed.");
                $fdisplay(__aesl__err,"Unknown token \"%s\" in file \"%s\"!", __aesl__token, TV_IN);
                $finish;
            end
            read_token(__aesl__fp, __aesl__token);  // skip ","
            if (__aesl__token == ",") begin
                read_token(__aesl__fp, __aesl__token);
            end
            else if (__aesl__token != "}") begin
                $display("Illegal tv format of file \"%s\"!", TV_IN);
                $display("ERROR: Simulation using HLS TB failed.");
                $fdisplay(__aesl__err,"Illegal tv format of file \"%s\"!", TV_IN);
                $finish;
            end
        end
        @(posedge __aesl__clock0);
        read_token(__aesl__fp, __aesl__token);  // skip ","
        if (__aesl__token == ",") begin
            read_token(__aesl__fp, __aesl__token);
        end
        else if (__aesl__token != "]") begin
            $display("Expected end ']' in file \"%s\"!", TV_IN);
        end
    end
    $fclose(__aesl__fp);
end

// check tv out
initial begin : __aesl__check_process
    integer __aesl__fp;
    integer __aesl__ret;
    integer __aesl__cid;
    reg __aesl__ig0;
    reg __aesl__ig1;
    reg [127:0] __aesl__token;
    integer __aesl__i;
    reg __aesl__ok;
    // check output
    __aesl__fp = $fopen(TV_OUT, "r");
    if (__aesl__fp == 0) begin  // failed to open file
        $display("Failed to open file \"%s\"!", TV_OUT);
        $display("ERROR: Simulation using HLS TB failed.");
        $fdisplay(__aesl__err,"Failed to open file \"%s\"!", TV_OUT);
        $finish;
    end
    @(posedge __aesl__clock0);
    __aesl__cid = 0;
    read_token(__aesl__fp, __aesl__token);
    if (__aesl__token != "[") begin  // illegal format
        $display("Illegal tv format of file \"%s\"!", TV_OUT);
        $display("ERROR: Simulation using HLS TB failed.");
        $fdisplay(__aesl__err, "Cycle #%0d: Failed to open file \"%s\"!", __aesl__cid, TV_OUT);
        $finish;
    end
    read_token(__aesl__fp, __aesl__token);
    while (__aesl__token != "]" && __aesl__token != "") begin
        @(posedge __aesl__clock0);
        __aesl__ig0 = (__aesl__cid < 4);
        __aesl__ig1 = (reset == 1);
        __aesl__cid = __aesl__cid + 1;
        if (__aesl__token != "{") begin  // illegal format
            $display("Illegal tv format of file \"%s\"!", TV_OUT);
            $display("ERROR: Simulation using HLS TB failed.");
            $fdisplay(__aesl__err, "Cycle #%0d: Failed to open file \"%s\"!", __aesl__cid, TV_OUT);
            $finish;
        end
        read_token(__aesl__fp, __aesl__token);
        while (__aesl__token != "}") begin
                if ((__aesl__token[63 : 8] == "outLeds") && (__aesl__token[71 : 64] == 34) && (__aesl__token[7 : 0] == 34)) begin
                    read_token(__aesl__fp, __aesl__token);
                    if (__aesl__token != ":") begin  // illegal format
                        $display("Illegal tv format of file \"%s\"!", TV_OUT);
                        $display("ERROR: Simulation using HLS TB failed.");
                        $fdisplay(__aesl__err, "Cycle #%0d: Failed to open file \"%s\"!", __aesl__cid, TV_OUT);
                        $finish;
                    end
                    read_token(__aesl__fp, __aesl__token);
                    rm_quoation(__aesl__token);
                    __aesl__ret = $sscanf(__aesl__token, "%b", __aesl__outLeds);
                    if (__aesl__ret != 1) begin
                        $display("Failed to parse token!");
                        $display("ERROR: Simulation using HLS TB failed.");
                        $fdisplay(__aesl__err, "Cycle #%0d: Failed to open file \"%s\"!", __aesl__cid, TV_OUT);
                        $finish;
                    end
                    if (!__aesl__ig0 && !__aesl__ig1) begin
                        __aesl__i = 0;
                        __aesl__ok = 1;
                        while (__aesl__i < 4 && __aesl__ok) begin
                            if (__aesl__outLeds[__aesl__i] === 0 && outLeds[__aesl__i] !== 0 ||
                                __aesl__outLeds[__aesl__i] === 1 && outLeds[__aesl__i] !== 1) begin
                                __aesl__ok = 0;
                            end
                            __aesl__i = __aesl__i + 1;
                        end
                        if (!__aesl__ok) begin
                            $fdisplay(__aesl__err, "Cycle #%0d: signal \"outLeds\": %0b -- %0b (expected) unmatched.", __aesl__cid, outLeds, __aesl__outLeds);
                        end
                    end
                end
                else begin  // unknown token
                    $display("Unknown token \"%s\" in file \"%s\"!", __aesl__token, TV_OUT);
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err, "Cycle #%0d: Failed to open file \"%s\"!", __aesl__cid, TV_OUT);
                    $finish;
                end
                read_token(__aesl__fp, __aesl__token);  // skip ","
                if (__aesl__token == ",") begin
                    read_token(__aesl__fp, __aesl__token);
                end
                else if (__aesl__token != "}") begin
                    $display("Illegal tv format of file \"%s\"!", TV_OUT);
                    $display("ERROR: Simulation using HLS TB failed.");
                    $fdisplay(__aesl__err, "Cycle #%0d: Failed to open file \"%s\"!", __aesl__cid, TV_OUT);
                    $finish;
                end
            end
            read_token(__aesl__fp, __aesl__token);  // skip ","
            if (__aesl__token == ",") begin
                read_token(__aesl__fp, __aesl__token);
            end
            else if (__aesl__token != "]") begin
                $display("Expected end ']' in file \"%s\"!", TV_OUT);
            end
        end
        $fclose(__aesl__fp);
        $fclose(__aesl__err);
        $display("Simulation done!");
        $finish;
    end

    endmodule

