webtalk_init -webtalk_dir D:\\Xilinx\\Assignment_2\\HLS_labs\\lab4\\audio\\audio.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-09-27 11:01:46" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "s8c7kltk7n8pmmca0e337ge2la" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1538036786032" -context "sdk\\\\bsp/1538036786032"
webtalk_add_data -client sdk -key hwid -value "1538036450316" -context "sdk\\\\bsp/1538036786032"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1538036786032"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1538036786032"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1538036786032"
webtalk_add_data -client sdk -key uid -value "1538037118657" -context "sdk\\\\application/1538037118657"
webtalk_add_data -client sdk -key hwid -value "1538036450316" -context "sdk\\\\application/1538037118657"
webtalk_add_data -client sdk -key bspid -value "1538036786032" -context "sdk\\\\application/1538037118657"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1538037118657"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1538037118657"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1538037118657"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1538037118657"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1538037118657"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1538037118657"
webtalk_add_data -client sdk -key projSize -value "223.54296875" -context "sdk\\\\application/1538037118657"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1538038906035"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1538038906035"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1538038906035"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1538038906035"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1538038906035"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1538038906035"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1538038906035"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1538038906035"
webtalk_transmit -clientid 2363981978 -regid "" -xml D:\\Xilinx\\Assignment_2\\HLS_labs\\lab4\\audio\\audio.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Xilinx\\Assignment_2\\HLS_labs\\lab4\\audio\\audio.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Xilinx\\Assignment_2\\HLS_labs\\lab4\\audio\\audio.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
