// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

module AESL_axi_slave_eqio (
    clk,
    reset,
    TRAN_s_axi_eqio_AWADDR,
    TRAN_s_axi_eqio_AWVALID,
    TRAN_s_axi_eqio_AWREADY,
    TRAN_s_axi_eqio_WVALID,
    TRAN_s_axi_eqio_WREADY,
    TRAN_s_axi_eqio_WDATA,
    TRAN_s_axi_eqio_WSTRB,
    TRAN_s_axi_eqio_ARADDR,
    TRAN_s_axi_eqio_ARVALID,
    TRAN_s_axi_eqio_ARREADY,
    TRAN_s_axi_eqio_RVALID,
    TRAN_s_axi_eqio_RREADY,
    TRAN_s_axi_eqio_RDATA,
    TRAN_s_axi_eqio_RRESP,
    TRAN_s_axi_eqio_BVALID,
    TRAN_s_axi_eqio_BREADY,
    TRAN_s_axi_eqio_BRESP,
    TRAN_eqio_write_data_finish,
    TRAN_eqio_start_in,
    TRAN_eqio_idle_out,
    TRAN_eqio_ready_out,
    TRAN_eqio_ready_in,
    TRAN_eqio_done_out,
    TRAN_eqio_write_start_in   ,
    TRAN_eqio_write_start_finish,
    TRAN_eqio_interrupt,
    TRAN_eqio_transaction_done_in
    );

//------------------------Parameter----------------------
`define TV_IN_b0 "../tv/cdatafile/c.eq.autotvin_b0.dat"
`define TV_IN_b1 "../tv/cdatafile/c.eq.autotvin_b1.dat"
`define TV_IN_b2 "../tv/cdatafile/c.eq.autotvin_b2.dat"
`define TV_IN_a1 "../tv/cdatafile/c.eq.autotvin_a1.dat"
`define TV_IN_a2 "../tv/cdatafile/c.eq.autotvin_a2.dat"
parameter ADDR_WIDTH = 6;
parameter DATA_WIDTH = 32;
parameter b0_DEPTH = 1;
reg [31 : 0] b0_OPERATE_DEPTH = 0;
parameter b0_c_bitwidth = 32;
parameter b1_DEPTH = 1;
reg [31 : 0] b1_OPERATE_DEPTH = 0;
parameter b1_c_bitwidth = 32;
parameter b2_DEPTH = 1;
reg [31 : 0] b2_OPERATE_DEPTH = 0;
parameter b2_c_bitwidth = 32;
parameter a1_DEPTH = 1;
reg [31 : 0] a1_OPERATE_DEPTH = 0;
parameter a1_c_bitwidth = 32;
parameter a2_DEPTH = 1;
reg [31 : 0] a2_OPERATE_DEPTH = 0;
parameter a2_c_bitwidth = 32;
parameter START_ADDR = 0;
parameter eq_continue_addr = 0;
parameter eq_auto_start_addr = 0;
parameter b0_data_in_addr = 16;
parameter b1_data_in_addr = 24;
parameter b2_data_in_addr = 32;
parameter a1_data_in_addr = 40;
parameter a2_data_in_addr = 48;
parameter STATUS_ADDR = 0;

output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_eqio_AWADDR;
output  TRAN_s_axi_eqio_AWVALID;
input  TRAN_s_axi_eqio_AWREADY;
output  TRAN_s_axi_eqio_WVALID;
input  TRAN_s_axi_eqio_WREADY;
output [DATA_WIDTH - 1 : 0] TRAN_s_axi_eqio_WDATA;
output [DATA_WIDTH/8 - 1 : 0] TRAN_s_axi_eqio_WSTRB;
output [ADDR_WIDTH - 1 : 0] TRAN_s_axi_eqio_ARADDR;
output  TRAN_s_axi_eqio_ARVALID;
input  TRAN_s_axi_eqio_ARREADY;
input  TRAN_s_axi_eqio_RVALID;
output  TRAN_s_axi_eqio_RREADY;
input [DATA_WIDTH - 1 : 0] TRAN_s_axi_eqio_RDATA;
input [2 - 1 : 0] TRAN_s_axi_eqio_RRESP;
input  TRAN_s_axi_eqio_BVALID;
output  TRAN_s_axi_eqio_BREADY;
input [2 - 1 : 0] TRAN_s_axi_eqio_BRESP;
output TRAN_eqio_write_data_finish;
input     clk;
input     reset;
input     TRAN_eqio_start_in;
output    TRAN_eqio_done_out;
output    TRAN_eqio_ready_out;
input     TRAN_eqio_ready_in;
output    TRAN_eqio_idle_out;
input  TRAN_eqio_write_start_in   ;
output TRAN_eqio_write_start_finish;
input     TRAN_eqio_interrupt;
input     TRAN_eqio_transaction_done_in;

reg [ADDR_WIDTH - 1 : 0] AWADDR_reg = 0;
reg  AWVALID_reg = 0;
reg  WVALID_reg = 0;
reg [DATA_WIDTH - 1 : 0] WDATA_reg = 0;
reg [DATA_WIDTH/8 - 1 : 0] WSTRB_reg = 0;
reg [ADDR_WIDTH - 1 : 0] ARADDR_reg = 0;
reg  ARVALID_reg = 0;
reg  RREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] RDATA_reg = 0;
reg  BREADY_reg = 0;
reg [DATA_WIDTH - 1 : 0] mem_b0 [b0_DEPTH - 1 : 0];
reg b0_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_b1 [b1_DEPTH - 1 : 0];
reg b1_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_b2 [b2_DEPTH - 1 : 0];
reg b2_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_a1 [a1_DEPTH - 1 : 0];
reg a1_write_data_finish;
reg [DATA_WIDTH - 1 : 0] mem_a2 [a2_DEPTH - 1 : 0];
reg a2_write_data_finish;
reg AESL_ready_out_index_reg = 0;
reg AESL_write_start_finish = 0;
reg AESL_ready_reg;
reg ready_initial;
reg AESL_done_index_reg = 0;
reg AESL_idle_index_reg = 0;
reg AESL_auto_restart_index_reg;
reg process_0_finish = 0;
reg process_1_finish = 0;
reg process_2_finish = 0;
reg process_3_finish = 0;
reg process_4_finish = 0;
reg process_5_finish = 0;
reg process_6_finish = 0;
//write b0 reg
reg [31 : 0] write_b0_count = 0;
reg write_b0_run_flag = 0;
reg write_one_b0_data_done = 0;
//write b1 reg
reg [31 : 0] write_b1_count = 0;
reg write_b1_run_flag = 0;
reg write_one_b1_data_done = 0;
//write b2 reg
reg [31 : 0] write_b2_count = 0;
reg write_b2_run_flag = 0;
reg write_one_b2_data_done = 0;
//write a1 reg
reg [31 : 0] write_a1_count = 0;
reg write_a1_run_flag = 0;
reg write_one_a1_data_done = 0;
//write a2 reg
reg [31 : 0] write_a2_count = 0;
reg write_a2_run_flag = 0;
reg write_one_a2_data_done = 0;
reg [31 : 0] write_start_count = 0;
reg write_start_run_flag = 0;

//===================process control=================
reg [31 : 0] ongoing_process_number = 0;
//process number depends on how much processes needed.
reg process_busy = 0;

//=================== signal connection ==============
assign TRAN_s_axi_eqio_AWADDR = AWADDR_reg;
assign TRAN_s_axi_eqio_AWVALID = AWVALID_reg;
assign TRAN_s_axi_eqio_WVALID = WVALID_reg;
assign TRAN_s_axi_eqio_WDATA = WDATA_reg;
assign TRAN_s_axi_eqio_WSTRB = WSTRB_reg;
assign TRAN_s_axi_eqio_ARADDR = ARADDR_reg;
assign TRAN_s_axi_eqio_ARVALID = ARVALID_reg;
assign TRAN_s_axi_eqio_RREADY = RREADY_reg;
assign TRAN_s_axi_eqio_BREADY = BREADY_reg;
assign TRAN_eqio_write_start_finish = AESL_write_start_finish;
assign TRAN_eqio_done_out = AESL_done_index_reg;
assign TRAN_eqio_ready_out = AESL_ready_out_index_reg;
assign TRAN_eqio_idle_out = AESL_idle_index_reg;
assign TRAN_eqio_write_data_finish = 1 & b0_write_data_finish & b1_write_data_finish & b2_write_data_finish & a1_write_data_finish & a2_write_data_finish;
always @(TRAN_eqio_ready_in or ready_initial) 
begin
    AESL_ready_reg <= TRAN_eqio_ready_in | ready_initial;
end

always @(reset or process_0_finish or process_1_finish or process_2_finish or process_3_finish or process_4_finish or process_5_finish or process_6_finish ) begin
    if (reset == 0) begin
        ongoing_process_number <= 0;
    end
    else if (ongoing_process_number == 0 && process_0_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 1 && process_1_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 2 && process_2_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 3 && process_3_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 4 && process_4_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 5 && process_5_finish == 1) begin
            ongoing_process_number <= ongoing_process_number + 1;
    end
    else if (ongoing_process_number == 6 && process_6_finish == 1) begin
            ongoing_process_number <= 0;
    end
end

task count_c_data_four_byte_num_by_bitwidth;
input  integer bitwidth;
output integer num;
integer factor;
integer i;
begin
    factor = 32;
    for (i = 1; i <= 32; i = i + 1) begin
        if (bitwidth <= factor && bitwidth > factor - 32) begin
            num = i;
        end
        factor = factor + 32;
    end
end    
endtask

task count_seperate_factor_by_bitwidth;
input  integer bitwidth;
output integer factor;
begin
    if (bitwidth <= 8 ) begin
        factor=4;
    end
    if (bitwidth <= 16 & bitwidth > 8 ) begin
        factor=2;
    end
    if (bitwidth <= 32 & bitwidth > 16 ) begin
        factor=1;
    end
    if (bitwidth <= 1024 & bitwidth > 32 ) begin
        factor=1;
    end
end    
endtask

task count_operate_depth_by_bitwidth_and_depth;
input  integer bitwidth;
input  integer depth;
output integer operate_depth;
integer factor;
integer remain;
begin
    count_seperate_factor_by_bitwidth (bitwidth , factor);
    operate_depth = depth / factor;
    remain = depth % factor;
    if (remain > 0) begin
        operate_depth = operate_depth + 1;
    end
end    
endtask

task write; /*{{{*/
    input  reg [ADDR_WIDTH - 1:0] waddr;   // write address
    input  reg [DATA_WIDTH - 1:0] wdata;   // write data
    output reg wresp;
    reg aw_flag;
    reg w_flag;
    reg [DATA_WIDTH/8 - 1:0] wstrb_reg;
    integer i;
begin 
    wresp = 0;
    aw_flag = 0;
    w_flag = 0;
//=======================one single write operate======================
    AWADDR_reg <= waddr;
    AWVALID_reg <= 1;
    WDATA_reg <= wdata;
    WVALID_reg <= 1;
    for (i = 0; i < DATA_WIDTH/8; i = i + 1) begin
        wstrb_reg [i] = 1;
    end    
    WSTRB_reg <= wstrb_reg;
    while (!(aw_flag && w_flag)) begin
        @(posedge clk);
        if (aw_flag != 1)
            aw_flag = TRAN_s_axi_eqio_AWREADY & AWVALID_reg;
        if (w_flag != 1)
            w_flag = TRAN_s_axi_eqio_WREADY & WVALID_reg;
        AWVALID_reg <= !aw_flag;
        WVALID_reg <= !w_flag;
    end

    BREADY_reg <= 1;
    while (TRAN_s_axi_eqio_BVALID != 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    BREADY_reg <= 0;
    if (TRAN_s_axi_eqio_BRESP === 2'b00) begin
        wresp = 1;
        //input success. in fact BRESP is always 2'b00
    end   
//=======================one single write operate======================

end
endtask/*}}}*/

task read (/*{{{*/
    input  [ADDR_WIDTH - 1:0] raddr ,   // write address
    output [DATA_WIDTH - 1:0] RDATA_result ,
    output rresp
);
begin 
    rresp = 0;
//=======================one single read operate======================
    ARADDR_reg <= raddr;
    ARVALID_reg <= 1;
    while (TRAN_s_axi_eqio_ARREADY !== 1) begin
        @(posedge clk);
    end
    @(posedge clk);
    ARVALID_reg <= 0;
    RREADY_reg <= 1;
    while (TRAN_s_axi_eqio_RVALID !== 1) begin
        //wait for response 
        @(posedge clk);
    end
    @(posedge clk);
    RDATA_result  <= TRAN_s_axi_eqio_RDATA;
    RREADY_reg <= 0;
    if (TRAN_s_axi_eqio_RRESP === 2'b00 ) begin
        rresp <= 1;
        //output success. in fact RRESP is always 2'b00
    end  
    @(posedge clk);

//=======================one single read operate end======================

end
endtask/*}}}*/

initial begin : ready_initial_process
    ready_initial = 0;
    wait(reset === 1);
    @(posedge clk);
    ready_initial = 1;
    @(posedge clk);
    ready_initial = 0;
end

initial begin : update_status
    integer process_num ;
    integer read_status_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 0;
    while (1) begin
        process_0_finish = 0;
        AESL_done_index_reg         <= 0;
        AESL_ready_out_index_reg        <= 0;
        if (ongoing_process_number === process_num && process_busy === 0) begin
            process_busy = 1;
            read (STATUS_ADDR, RDATA_reg, read_status_resp);
                AESL_done_index_reg         <= RDATA_reg[1 : 1];
                AESL_ready_out_index_reg    <= RDATA_reg[1 : 1];
                AESL_idle_index_reg         <= RDATA_reg[2 : 2];
            process_0_finish = 1;
            process_busy = 0;
        end 
        @(posedge clk);
    end
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        b0_write_data_finish <= 0;
        write_b0_run_flag <= 0; 
        write_b0_count = 0;
        count_operate_depth_by_bitwidth_and_depth (b0_c_bitwidth, b0_DEPTH, b0_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_eqio_start_in === 1) begin
            b0_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_b0_run_flag <= 1; 
            write_b0_count = 0;
        end
        if (write_one_b0_data_done === 1) begin
            write_b0_count = write_b0_count + 1;
            if (write_b0_count == b0_OPERATE_DEPTH) begin
                write_b0_run_flag <= 0; 
                b0_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_b0
    integer write_b0_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] b0_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = b0_c_bitwidth;
    process_num = 1;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_1_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_b0_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write b0 data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (b0_c_bitwidth < 32) begin
                        b0_data_tmp_reg = mem_b0[write_b0_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < b0_c_bitwidth) begin
                                b0_data_tmp_reg[j] = mem_b0[write_b0_count][i*32 + j];
                            end
                            else begin
                                b0_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (b0_data_in_addr + write_b0_count * four_byte_num * 4 + i * 4, b0_data_tmp_reg, write_b0_resp);
                end
                process_busy = 0;
                write_one_b0_data_done <= 1;
                @(posedge clk);
                write_one_b0_data_done <= 0;
            end   
            process_1_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        b1_write_data_finish <= 0;
        write_b1_run_flag <= 0; 
        write_b1_count = 0;
        count_operate_depth_by_bitwidth_and_depth (b1_c_bitwidth, b1_DEPTH, b1_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_eqio_start_in === 1) begin
            b1_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_b1_run_flag <= 1; 
            write_b1_count = 0;
        end
        if (write_one_b1_data_done === 1) begin
            write_b1_count = write_b1_count + 1;
            if (write_b1_count == b1_OPERATE_DEPTH) begin
                write_b1_run_flag <= 0; 
                b1_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_b1
    integer write_b1_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] b1_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = b1_c_bitwidth;
    process_num = 2;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_2_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_b1_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write b1 data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (b1_c_bitwidth < 32) begin
                        b1_data_tmp_reg = mem_b1[write_b1_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < b1_c_bitwidth) begin
                                b1_data_tmp_reg[j] = mem_b1[write_b1_count][i*32 + j];
                            end
                            else begin
                                b1_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (b1_data_in_addr + write_b1_count * four_byte_num * 4 + i * 4, b1_data_tmp_reg, write_b1_resp);
                end
                process_busy = 0;
                write_one_b1_data_done <= 1;
                @(posedge clk);
                write_one_b1_data_done <= 0;
            end   
            process_2_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        b2_write_data_finish <= 0;
        write_b2_run_flag <= 0; 
        write_b2_count = 0;
        count_operate_depth_by_bitwidth_and_depth (b2_c_bitwidth, b2_DEPTH, b2_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_eqio_start_in === 1) begin
            b2_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_b2_run_flag <= 1; 
            write_b2_count = 0;
        end
        if (write_one_b2_data_done === 1) begin
            write_b2_count = write_b2_count + 1;
            if (write_b2_count == b2_OPERATE_DEPTH) begin
                write_b2_run_flag <= 0; 
                b2_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_b2
    integer write_b2_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] b2_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = b2_c_bitwidth;
    process_num = 3;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_3_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_b2_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write b2 data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (b2_c_bitwidth < 32) begin
                        b2_data_tmp_reg = mem_b2[write_b2_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < b2_c_bitwidth) begin
                                b2_data_tmp_reg[j] = mem_b2[write_b2_count][i*32 + j];
                            end
                            else begin
                                b2_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (b2_data_in_addr + write_b2_count * four_byte_num * 4 + i * 4, b2_data_tmp_reg, write_b2_resp);
                end
                process_busy = 0;
                write_one_b2_data_done <= 1;
                @(posedge clk);
                write_one_b2_data_done <= 0;
            end   
            process_3_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        a1_write_data_finish <= 0;
        write_a1_run_flag <= 0; 
        write_a1_count = 0;
        count_operate_depth_by_bitwidth_and_depth (a1_c_bitwidth, a1_DEPTH, a1_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_eqio_start_in === 1) begin
            a1_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_a1_run_flag <= 1; 
            write_a1_count = 0;
        end
        if (write_one_a1_data_done === 1) begin
            write_a1_count = write_a1_count + 1;
            if (write_a1_count == a1_OPERATE_DEPTH) begin
                write_a1_run_flag <= 0; 
                a1_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_a1
    integer write_a1_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] a1_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = a1_c_bitwidth;
    process_num = 4;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_4_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_a1_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write a1 data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (a1_c_bitwidth < 32) begin
                        a1_data_tmp_reg = mem_a1[write_a1_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < a1_c_bitwidth) begin
                                a1_data_tmp_reg[j] = mem_a1[write_a1_count][i*32 + j];
                            end
                            else begin
                                a1_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (a1_data_in_addr + write_a1_count * four_byte_num * 4 + i * 4, a1_data_tmp_reg, write_a1_resp);
                end
                process_busy = 0;
                write_one_a1_data_done <= 1;
                @(posedge clk);
                write_one_a1_data_done <= 0;
            end   
            process_4_finish <= 1;
        end
        @(posedge clk);
    end    
end
always @(reset or posedge clk) begin
    if (reset == 0) begin
        a2_write_data_finish <= 0;
        write_a2_run_flag <= 0; 
        write_a2_count = 0;
        count_operate_depth_by_bitwidth_and_depth (a2_c_bitwidth, a2_DEPTH, a2_OPERATE_DEPTH);
    end
    else begin
        if (TRAN_eqio_start_in === 1) begin
            a2_write_data_finish <= 0;
        end
        if (AESL_ready_reg === 1) begin
            write_a2_run_flag <= 1; 
            write_a2_count = 0;
        end
        if (write_one_a2_data_done === 1) begin
            write_a2_count = write_a2_count + 1;
            if (write_a2_count == a2_OPERATE_DEPTH) begin
                write_a2_run_flag <= 0; 
                a2_write_data_finish <= 1;
            end
        end
    end
end

initial begin : write_a2
    integer write_a2_resp;
    integer process_num ;
    integer get_ack;
    integer four_byte_num;
    integer c_bitwidth;
    integer i;
    integer j;
    reg [31 : 0] a2_data_tmp_reg;
    wait(reset === 1);
    @(posedge clk);
    c_bitwidth = a2_c_bitwidth;
    process_num = 5;
    count_c_data_four_byte_num_by_bitwidth (c_bitwidth , four_byte_num) ;
    while (1) begin
        process_5_finish <= 0;

        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            get_ack = 1;
            if (write_a2_run_flag === 1 && get_ack === 1) begin
                process_busy = 1;
                //write a2 data 
                for (i = 0 ; i < four_byte_num ; i = i+1) begin
                    if (a2_c_bitwidth < 32) begin
                        a2_data_tmp_reg = mem_a2[write_a2_count];
                    end
                    else begin
                        for (j=0 ; j<32 ; j = j + 1) begin
                            if (i*32 + j < a2_c_bitwidth) begin
                                a2_data_tmp_reg[j] = mem_a2[write_a2_count][i*32 + j];
                            end
                            else begin
                                a2_data_tmp_reg[j] = 0;
                            end
                        end
                    end
                    write (a2_data_in_addr + write_a2_count * four_byte_num * 4 + i * 4, a2_data_tmp_reg, write_a2_resp);
                end
                process_busy = 0;
                write_one_a2_data_done <= 1;
                @(posedge clk);
                write_one_a2_data_done <= 0;
            end   
            process_5_finish <= 1;
        end
        @(posedge clk);
    end    
end

always @(reset or posedge clk) begin
    if (reset == 0) begin
        write_start_run_flag <= 0; 
        write_start_count <= 0;
    end
    else begin
        if (write_start_count >= 48007) begin
            write_start_run_flag <= 0; 
        end
        else if (TRAN_eqio_write_start_in === 1) begin
            write_start_run_flag <= 1; 
        end
        if (AESL_write_start_finish === 1) begin
            write_start_count <= write_start_count + 1;
            write_start_run_flag <= 0; 
        end
    end
end

initial begin : write_start
    reg [DATA_WIDTH - 1 : 0] write_start_tmp;
    integer process_num;
    integer write_start_resp;
    wait(reset === 1);
    @(posedge clk);
    process_num = 6;
    while (1) begin
        process_6_finish = 0;
        if (ongoing_process_number === process_num && process_busy === 0 ) begin
            if (write_start_run_flag === 1) begin
                process_busy = 1;
                write_start_tmp=0;
                write_start_tmp[0 : 0] = 1;
                write (START_ADDR, write_start_tmp, write_start_resp);
                process_busy = 0;
                AESL_write_start_finish <= 1;
                @(posedge clk);
                AESL_write_start_finish <= 0;
            end
            process_6_finish <= 1;
        end 
        @(posedge clk);
    end
end

//------------------------Task and function-------------- 
task read_token; 
    input integer fp; 
    output reg [127 : 0] token;
    integer ret;
    begin
        token = "";
        ret = 0;
        ret = $fscanf(fp,"%s",token);
    end 
endtask 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_b0_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [b0_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (b0_c_bitwidth , factor);
  fp = $fopen(`TV_IN_b0 ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_b0); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < b0_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_b0 [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_b0 [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_b0 [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_b0 [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_b0 [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_b1_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [b1_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (b1_c_bitwidth , factor);
  fp = $fopen(`TV_IN_b1 ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_b1); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < b1_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_b1 [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_b1 [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_b1 [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_b1 [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_b1 [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_b2_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [b2_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (b2_c_bitwidth , factor);
  fp = $fopen(`TV_IN_b2 ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_b2); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < b2_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_b2 [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_b2 [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_b2 [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_b2 [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_b2 [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_a1_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [a1_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (a1_c_bitwidth , factor);
  fp = $fopen(`TV_IN_a1 ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_a1); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < a1_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_a1 [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_a1 [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_a1 [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_a1 [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_a1 [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
//------------------------Read file------------------------ 
 
// Read data from file 
initial begin : read_a2_file_process 
  integer fp; 
  integer ret; 
  integer factor; 
  reg [127 : 0] token; 
  reg [127 : 0] token_tmp; 
  //reg [a2_c_bitwidth - 1 : 0] token_tmp; 
  reg [DATA_WIDTH - 1 : 0] mem_tmp; 
  reg [ 8*5 : 1] str;
  integer transaction_idx; 
  integer i; 
  transaction_idx = 0; 
  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
  count_seperate_factor_by_bitwidth (a2_c_bitwidth , factor);
  fp = $fopen(`TV_IN_a2 ,"r"); 
  if(fp == 0) begin                               // Failed to open file 
      $display("Failed to open file \"%s\"!", `TV_IN_a2); 
      $finish; 
  end 
  read_token(fp, token); 
  if (token != "[[[runtime]]]") begin             // Illegal format 
      $display("ERROR: Simulation using HLS TB failed.");
      $finish; 
  end 
  read_token(fp, token); 
  while (token != "[[[/runtime]]]") begin 
      if (token != "[[transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token);                        // skip transaction number 
      @(posedge clk);
      # 0.2;
      while(AESL_ready_reg !== 1) begin
          @(posedge clk); 
          # 0.2;
      end
      for(i = 0; i < a2_DEPTH; i = i + 1) begin 
          read_token(fp, token); 
          ret = $sscanf(token, "0x%x", token_tmp); 
          if (factor == 4) begin
              if (i%factor == 0) begin
                  mem_tmp [7 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [15 : 8] = token_tmp;
              end
              if (i%factor == 2) begin
                  mem_tmp [23 : 16] = token_tmp;
              end
              if (i%factor == 3) begin
                  mem_tmp [31 : 24] = token_tmp;
                  mem_a2 [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1 : 0] = 0;
              end
          end
          if (factor == 2) begin
              if (i%factor == 0) begin
                  mem_tmp [15 : 0] = token_tmp;
              end
              if (i%factor == 1) begin
                  mem_tmp [31 : 16] = token_tmp;
                  mem_a2 [i/factor] = mem_tmp;
                  mem_tmp [DATA_WIDTH - 1: 0] = 0;
              end
          end
          if (factor == 1) begin
              mem_a2 [i] = token_tmp;
          end
      end 
      if (factor == 4) begin
          if (i%factor != 0) begin
              mem_a2 [i/factor] = mem_tmp;
          end
      end
      if (factor == 2) begin
          if (i%factor != 0) begin
              mem_a2 [i/factor] = mem_tmp;
          end
      end 
      read_token(fp, token); 
      if(token != "[[/transaction]]") begin 
          $display("ERROR: Simulation using HLS TB failed.");
          $finish; 
      end 
      read_token(fp, token); 
      transaction_idx = transaction_idx + 1; 
  end 
  $fclose(fp); 
end 
 
endmodule
