lappend pragmaStatus0 {pragma "INTERFACE" source "D:/Xilinx/Assignment_2/EQ_HLS/EQ.c" location "eq" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "D:/Xilinx/Assignment_2/EQ_HLS/EQ.c" location "eq" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "INTERFACE" source "D:/Xilinx/Assignment_2/EQ_HLS/EQ.c" location "eq" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "INTERFACE" source "D:/Xilinx/Assignment_2/EQ_HLS/EQ.c" location "eq" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "INTERFACE" source "D:/Xilinx/Assignment_2/EQ_HLS/EQ.c" location "eq" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "INTERFACE" source "D:/Xilinx/Assignment_2/EQ_HLS/EQ.c" location "eq" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "INTERFACE" source "D:/Xilinx/Assignment_2/EQ_HLS/EQ.c" location "eq" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "INTERFACE" source "D:/Xilinx/Assignment_2/EQ_HLS/EQ.c" location "eq" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "INTERFACE" source "D:/Xilinx/Assignment_2/EQ_HLS/EQ.c" location "eq" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
