// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_eq (
int b0,
int b1,
int b2,
int a1,
int a2,
short band,
short sampleIn,
short* sampleOut);
