// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xeq.h"

extern XEq_Config XEq_ConfigTable[];

XEq_Config *XEq_LookupConfig(u16 DeviceId) {
	XEq_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XEQ_NUM_INSTANCES; Index++) {
		if (XEq_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XEq_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XEq_Initialize(XEq *InstancePtr, u16 DeviceId) {
	XEq_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XEq_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XEq_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

