<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="14">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>iosc_pulse</name>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>6</id>
              <name>internalPulse</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>iosc.internalPulse.Val</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>17</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_2">
          <Value>
            <Obj>
              <type>0</type>
              <id>8</id>
              <name>clockCounter_V_1</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>clockCounter.V</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>50</item>
          </oprand_edges>
          <opcode>alloca</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_3">
          <Value>
            <Obj>
              <type>0</type>
              <id>26</id>
              <name/>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>44</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="11" tracking_level="0" version="0">
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second class_id="12" tracking_level="0" version="0">
                    <count>1</count>
                    <item_version>0</item_version>
                    <item class_id="13" tracking_level="0" version="0">
                      <first class_id="14" tracking_level="0" version="0">
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>44</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>52</item>
            <item>53</item>
            <item>55</item>
          </oprand_edges>
          <opcode>write</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>29</id>
              <name/>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>45</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>45</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>57</item>
            <item>58</item>
            <item>203</item>
          </oprand_edges>
          <opcode>wait</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>30</id>
              <name/>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>60</item>
            <item>61</item>
          </oprand_edges>
          <opcode>store</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>31</id>
              <name/>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>46</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>46</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>62</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>33</id>
              <name>clockCounter_V_1_loa</name>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>55</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>55</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>63</item>
            <item>207</item>
          </oprand_edges>
          <opcode>load</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>34</id>
              <name>tmp</name>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>50</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>50</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_fu_101_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>64</item>
            <item>66</item>
          </oprand_edges>
          <opcode>icmp</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>35</id>
              <name/>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>50</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>50</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>67</item>
            <item>68</item>
            <item>69</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>37</id>
              <name>clockCounter_V</name>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>55</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>55</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>clockCounter.V</originalName>
              <rtlName>clockCounter_V_fu_107_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>77</item>
            <item>79</item>
          </oprand_edges>
          <opcode>add</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>38</id>
              <name/>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>56</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>56</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>5</count>
            <item_version>0</item_version>
            <item>80</item>
            <item>81</item>
            <item>82</item>
            <item>205</item>
            <item>210</item>
          </oprand_edges>
          <opcode>write</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_12">
          <Value>
            <Obj>
              <type>0</type>
              <id>39</id>
              <name/>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>55</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>55</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>83</item>
            <item>84</item>
            <item>211</item>
            <item>213</item>
          </oprand_edges>
          <opcode>store</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_13">
          <Value>
            <Obj>
              <type>0</type>
              <id>40</id>
              <name/>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>85</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_14">
          <Value>
            <Obj>
              <type>0</type>
              <id>42</id>
              <name/>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>53</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>5</count>
            <item_version>0</item_version>
            <item>70</item>
            <item>71</item>
            <item>73</item>
            <item>206</item>
            <item>208</item>
          </oprand_edges>
          <opcode>write</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_15">
          <Value>
            <Obj>
              <type>0</type>
              <id>43</id>
              <name/>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>74</item>
            <item>75</item>
            <item>209</item>
            <item>212</item>
          </oprand_edges>
          <opcode>store</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_16">
          <Value>
            <Obj>
              <type>0</type>
              <id>44</id>
              <name/>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>54</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>54</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>76</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_17">
          <Value>
            <Obj>
              <type>0</type>
              <id>46</id>
              <name/>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>58</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>58</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>86</item>
            <item>87</item>
            <item>204</item>
          </oprand_edges>
          <opcode>wait</opcode>
          <m_Display>0</m_Display>
        </item>
        <item class_id_reference="9" object_id="_18">
          <Value>
            <Obj>
              <type>0</type>
              <id>47</id>
              <name/>
              <fileName>SC_IO/ios.cpp</fileName>
              <fileDirectory>..</fileDirectory>
              <lineNumber>59</lineNumber>
              <contextFuncName>pulse</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>D:\Xilinx\Assignment_2\HLS_labs\lab7</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>SC_IO/ios.cpp</first>
                        <second>pulse</second>
                      </first>
                      <second>59</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>88</item>
          </oprand_edges>
          <opcode>br</opcode>
          <m_Display>0</m_Display>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>6</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_19">
          <Value>
            <Obj>
              <type>2</type>
              <id>49</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_20">
          <Value>
            <Obj>
              <type>2</type>
              <id>54</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
        <item class_id_reference="16" object_id="_21">
          <Value>
            <Obj>
              <type>2</type>
              <id>59</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>0</content>
        </item>
        <item class_id_reference="16" object_id="_22">
          <Value>
            <Obj>
              <type>2</type>
              <id>65</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1000</content>
        </item>
        <item class_id_reference="16" object_id="_23">
          <Value>
            <Obj>
              <type>2</type>
              <id>72</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_24">
          <Value>
            <Obj>
              <type>2</type>
              <id>78</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>10</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>5</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_25">
          <Obj>
            <type>3</type>
            <id>32</id>
            <name>_ZN7_ap_sc_7sc_core4waitEi.exit2</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>5</count>
            <item_version>0</item_version>
            <item>8</item>
            <item>26</item>
            <item>29</item>
            <item>30</item>
            <item>31</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_26">
          <Obj>
            <type>3</type>
            <id>36</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>3</count>
            <item_version>0</item_version>
            <item>33</item>
            <item>34</item>
            <item>35</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_27">
          <Obj>
            <type>3</type>
            <id>41</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>4</count>
            <item_version>0</item_version>
            <item>37</item>
            <item>38</item>
            <item>39</item>
            <item>40</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_28">
          <Obj>
            <type>3</type>
            <id>45</id>
            <name/>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>3</count>
            <item_version>0</item_version>
            <item>42</item>
            <item>43</item>
            <item>44</item>
          </node_objs>
        </item>
        <item class_id_reference="18" object_id="_29">
          <Obj>
            <type>3</type>
            <id>48</id>
            <name>_ZN7_ap_sc_7sc_core4waitEi.exit</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>2</count>
            <item_version>0</item_version>
            <item>46</item>
            <item>47</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>44</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_30">
          <id>50</id>
          <edge_type>1</edge_type>
          <source_obj>49</source_obj>
          <sink_obj>8</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>53</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>26</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>55</id>
          <edge_type>1</edge_type>
          <source_obj>54</source_obj>
          <sink_obj>26</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>58</id>
          <edge_type>1</edge_type>
          <source_obj>49</source_obj>
          <sink_obj>29</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>60</id>
          <edge_type>1</edge_type>
          <source_obj>59</source_obj>
          <sink_obj>30</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>61</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>30</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>62</id>
          <edge_type>2</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>31</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>63</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>33</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>64</id>
          <edge_type>1</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>34</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>66</id>
          <edge_type>1</edge_type>
          <source_obj>65</source_obj>
          <sink_obj>34</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>67</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>35</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>68</id>
          <edge_type>2</edge_type>
          <source_obj>41</source_obj>
          <sink_obj>35</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>69</id>
          <edge_type>2</edge_type>
          <source_obj>45</source_obj>
          <sink_obj>35</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>71</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>73</id>
          <edge_type>1</edge_type>
          <source_obj>72</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>74</id>
          <edge_type>1</edge_type>
          <source_obj>59</source_obj>
          <sink_obj>43</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>75</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>43</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>76</id>
          <edge_type>2</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>44</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>77</id>
          <edge_type>1</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>37</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>79</id>
          <edge_type>1</edge_type>
          <source_obj>78</source_obj>
          <sink_obj>37</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>81</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>38</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>82</id>
          <edge_type>1</edge_type>
          <source_obj>54</source_obj>
          <sink_obj>38</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>83</id>
          <edge_type>1</edge_type>
          <source_obj>37</source_obj>
          <sink_obj>39</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>84</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>39</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_54">
          <id>85</id>
          <edge_type>2</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>40</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_55">
          <id>87</id>
          <edge_type>1</edge_type>
          <source_obj>49</source_obj>
          <sink_obj>46</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_56">
          <id>88</id>
          <edge_type>2</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>47</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_57">
          <id>197</id>
          <edge_type>2</edge_type>
          <source_obj>32</source_obj>
          <sink_obj>36</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_58">
          <id>198</id>
          <edge_type>2</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>45</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_59">
          <id>199</id>
          <edge_type>2</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>41</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_60">
          <id>200</id>
          <edge_type>2</edge_type>
          <source_obj>41</source_obj>
          <sink_obj>48</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_61">
          <id>201</id>
          <edge_type>2</edge_type>
          <source_obj>45</source_obj>
          <sink_obj>48</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_62">
          <id>202</id>
          <edge_type>2</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>36</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_63">
          <id>203</id>
          <edge_type>4</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>29</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_64">
          <id>204</id>
          <edge_type>4</edge_type>
          <source_obj>29</source_obj>
          <sink_obj>46</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_65">
          <id>205</id>
          <edge_type>4</edge_type>
          <source_obj>29</source_obj>
          <sink_obj>38</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_66">
          <id>206</id>
          <edge_type>4</edge_type>
          <source_obj>29</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_67">
          <id>207</id>
          <edge_type>4</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>33</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_68">
          <id>208</id>
          <edge_type>4</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>42</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_69">
          <id>209</id>
          <edge_type>4</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>43</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_70">
          <id>210</id>
          <edge_type>4</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>38</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_71">
          <id>211</id>
          <edge_type>4</edge_type>
          <source_obj>30</source_obj>
          <sink_obj>39</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_72">
          <id>212</id>
          <edge_type>4</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>43</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_73">
          <id>213</id>
          <edge_type>4</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>39</sink_obj>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>3</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_74">
        <mId>1</mId>
        <mTag>iosc::pulse</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>2</count>
          <item_version>0</item_version>
          <item>2</item>
          <item>3</item>
        </sub_regions>
        <basic_blocks>
          <count>0</count>
          <item_version>0</item_version>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>3</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_75">
        <mId>2</mId>
        <mTag>Entry</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>32</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>1</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
      <item class_id_reference="22" object_id="_76">
        <mId>3</mId>
        <mTag>Loop 1</mTag>
        <mType>1</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>4</count>
          <item_version>0</item_version>
          <item>36</item>
          <item>41</item>
          <item>45</item>
          <item>48</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>1</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_77">
      <states class_id="25" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_78">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>21</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_79">
              <id>8</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_80">
              <id>9</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_81">
              <id>10</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_82">
              <id>11</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_83">
              <id>12</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_84">
              <id>13</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_85">
              <id>14</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_86">
              <id>15</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_87">
              <id>16</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_88">
              <id>17</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_89">
              <id>18</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_90">
              <id>19</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_91">
              <id>20</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_92">
              <id>21</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_93">
              <id>22</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_94">
              <id>23</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_95">
              <id>24</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_96">
              <id>25</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_97">
              <id>26</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_98">
              <id>27</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_99">
              <id>28</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_100">
          <id>2</id>
          <operations>
            <count>3</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_101">
              <id>29</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_102">
              <id>30</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_103">
              <id>31</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="26" object_id="_104">
          <id>3</id>
          <operations>
            <count>12</count>
            <item_version>0</item_version>
            <item class_id_reference="28" object_id="_105">
              <id>33</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_106">
              <id>34</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_107">
              <id>35</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_108">
              <id>37</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_109">
              <id>38</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_110">
              <id>39</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_111">
              <id>40</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_112">
              <id>42</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_113">
              <id>43</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_114">
              <id>44</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_115">
              <id>46</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_116">
              <id>47</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>3</count>
        <item_version>0</item_version>
        <item class_id="30" tracking_level="1" version="0" object_id="_117">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="31" tracking_level="0" version="0">
            <id>10</id>
            <sop class_id="32" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="33" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_118">
          <inState>2</inState>
          <outState>3</outState>
          <condition>
            <id>12</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="30" object_id="_119">
          <inState>3</inState>
          <outState>3</outState>
          <condition>
            <id>14</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="34" tracking_level="1" version="0" object_id="_120">
      <dp_component_resource class_id="35" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_resource>
      <dp_expression_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="36" tracking_level="0" version="0">
          <first>clockCounter_V_fu_107_p2 ( + ) </first>
          <second class_id="37" tracking_level="0" version="0">
            <count>4</count>
            <item_version>0</item_version>
            <item class_id="38" tracking_level="0" version="0">
              <first>(0P0)</first>
              <second>10</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>35</second>
            </item>
            <item>
              <first>LUT</first>
              <second>15</second>
            </item>
          </second>
        </item>
        <item>
          <first>tmp_fu_101_p2 ( icmp ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>10</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>6</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>5</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>ap_NS_fsm</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>4</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>4</second>
            </item>
            <item>
              <first>LUT</first>
              <second>21</second>
            </item>
          </second>
        </item>
        <item>
          <first>clockCounter_V_1_fu_80</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>10</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>20</second>
            </item>
            <item>
              <first>LUT</first>
              <second>9</second>
            </item>
          </second>
        </item>
        <item>
          <first>internalPulse</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>3</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>3</second>
            </item>
            <item>
              <first>LUT</first>
              <second>15</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>2</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>3</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>3</second>
            </item>
          </second>
        </item>
        <item>
          <first>clockCounter_V_1_fu_80</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>10</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>10</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_component_map class_id="39" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_map>
      <dp_expression_map>
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="40" tracking_level="0" version="0">
          <first>clockCounter_V_fu_107_p2 ( + ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>37</item>
          </second>
        </item>
        <item>
          <first>tmp_fu_101_p2 ( icmp ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>34</item>
          </second>
        </item>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="41" tracking_level="0" version="0">
      <count>17</count>
      <item_version>0</item_version>
      <item class_id="42" tracking_level="0" version="0">
        <first>8</first>
        <second class_id="43" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>26</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>29</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>30</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>31</first>
        <second>
          <first>1</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>33</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>34</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>35</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>37</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>38</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>39</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>40</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>42</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>43</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>44</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>46</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>47</first>
        <second>
          <first>2</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="44" tracking_level="0" version="0">
      <count>5</count>
      <item_version>0</item_version>
      <item class_id="45" tracking_level="0" version="0">
        <first>32</first>
        <second class_id="46" tracking_level="0" version="0">
          <first>0</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>36</first>
        <second>
          <first>2</first>
          <second>2</second>
        </second>
      </item>
      <item>
        <first>41</first>
        <second>
          <first>2</first>
          <second>2</second>
        </second>
      </item>
      <item>
        <first>45</first>
        <second>
          <first>2</first>
          <second>2</second>
        </second>
      </item>
      <item>
        <first>48</first>
        <second>
          <first>2</first>
          <second>2</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="47" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="48" tracking_level="1" version="0" object_id="_121">
        <region_name>__ssdm_reset__</region_name>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>32</item>
        </basic_blocks>
        <nodes>
          <count>6</count>
          <item_version>0</item_version>
          <item>23</item>
          <item>24</item>
          <item>25</item>
          <item>26</item>
          <item>27</item>
          <item>28</item>
        </nodes>
        <anchor_node>23</anchor_node>
        <region_type>1</region_type>
        <interval>0</interval>
        <pipe_depth>0</pipe_depth>
      </item>
    </regions>
    <dp_fu_nodes class_id="49" tracking_level="0" version="0">
      <count>7</count>
      <item_version>0</item_version>
      <item class_id="50" tracking_level="0" version="0">
        <first>80</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>84</first>
        <second>
          <count>3</count>
          <item_version>0</item_version>
          <item>26</item>
          <item>38</item>
          <item>42</item>
        </second>
      </item>
      <item>
        <first>93</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>30</item>
          <item>43</item>
        </second>
      </item>
      <item>
        <first>98</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>101</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
      <item>
        <first>107</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>37</item>
        </second>
      </item>
      <item>
        <first>113</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>39</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="52" tracking_level="0" version="0">
      <count>3</count>
      <item_version>0</item_version>
      <item class_id="53" tracking_level="0" version="0">
        <first>clockCounter_V_1_fu_80</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>clockCounter_V_fu_107</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>37</item>
        </second>
      </item>
      <item>
        <first>tmp_fu_101</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>34</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>4</count>
      <item_version>0</item_version>
      <item>
        <first>StgValue_33_store_fu_113</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>39</item>
        </second>
      </item>
      <item>
        <first>clockCounter_V_1_loa_load_fu_98</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>grp_store_fu_93</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>30</item>
          <item>43</item>
        </second>
      </item>
      <item>
        <first>grp_write_fu_84</first>
        <second>
          <count>3</count>
          <item_version>0</item_version>
          <item>26</item>
          <item>38</item>
          <item>42</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="54" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>118</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>1</count>
      <item_version>0</item_version>
      <item>
        <first>clockCounter_V_1_reg_118</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="55" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="56" tracking_level="0" version="0">
        <first>internalPulse</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>write</first>
            <second>
              <count>3</count>
              <item_version>0</item_version>
              <item>26</item>
              <item>42</item>
              <item>38</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core class_id="57" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </port2core>
    <node2core>
      <count>0</count>
      <item_version>0</item_version>
    </node2core>
  </syndb>
</boost_serialization>
