// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xiosc.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XIosc_CfgInitialize(XIosc *InstancePtr, XIosc_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Slv0_BaseAddress = ConfigPtr->Slv0_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XIosc_SetCtrl(XIosc *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XIosc_WriteReg(InstancePtr->Slv0_BaseAddress, XIOSC_SLV0_ADDR_CTRL_DATA, Data);
}

u32 XIosc_GetCtrl(XIosc *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XIosc_ReadReg(InstancePtr->Slv0_BaseAddress, XIOSC_SLV0_ADDR_CTRL_DATA);
    return Data;
}

