// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xiosc.h"

extern XIosc_Config XIosc_ConfigTable[];

XIosc_Config *XIosc_LookupConfig(u16 DeviceId) {
	XIosc_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XIOSC_NUM_INSTANCES; Index++) {
		if (XIosc_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XIosc_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XIosc_Initialize(XIosc *InstancePtr, u16 DeviceId) {
	XIosc_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XIosc_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XIosc_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

