// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xeq.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEq_CfgInitialize(XEq *InstancePtr, XEq_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Eqio_BaseAddress = ConfigPtr->Eqio_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEq_Start(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_AP_CTRL) & 0x80;
    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEq_IsDone(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEq_IsIdle(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEq_IsReady(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEq_EnableAutoRestart(XEq *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_AP_CTRL, 0x80);
}

void XEq_DisableAutoRestart(XEq *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_AP_CTRL, 0);
}

void XEq_Set_b0(XEq *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_B0_DATA, Data);
}

u32 XEq_Get_b0(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_B0_DATA);
    return Data;
}

void XEq_Set_b1(XEq *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_B1_DATA, Data);
}

u32 XEq_Get_b1(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_B1_DATA);
    return Data;
}

void XEq_Set_b2(XEq *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_B2_DATA, Data);
}

u32 XEq_Get_b2(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_B2_DATA);
    return Data;
}

void XEq_Set_a1(XEq *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_A1_DATA, Data);
}

u32 XEq_Get_a1(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_A1_DATA);
    return Data;
}

void XEq_Set_a2(XEq *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_A2_DATA, Data);
}

u32 XEq_Get_a2(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_A2_DATA);
    return Data;
}

void XEq_Set_band(XEq *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_BAND_DATA, Data);
}

u32 XEq_Get_band(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_BAND_DATA);
    return Data;
}

void XEq_Set_sampleIn(XEq *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_SAMPLEIN_DATA, Data);
}

u32 XEq_Get_sampleIn(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_SAMPLEIN_DATA);
    return Data;
}

u32 XEq_Get_sampleOut(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_SAMPLEOUT_DATA);
    return Data;
}

u32 XEq_Get_sampleOut_vld(XEq *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_SAMPLEOUT_CTRL);
    return Data & 0x1;
}

void XEq_InterruptGlobalEnable(XEq *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_GIE, 1);
}

void XEq_InterruptGlobalDisable(XEq *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_GIE, 0);
}

void XEq_InterruptEnable(XEq *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_IER);
    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_IER, Register | Mask);
}

void XEq_InterruptDisable(XEq *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_IER);
    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_IER, Register & (~Mask));
}

void XEq_InterruptClear(XEq *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEq_WriteReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_ISR, Mask);
}

u32 XEq_InterruptGetEnabled(XEq *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_IER);
}

u32 XEq_InterruptGetStatus(XEq *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEq_ReadReg(InstancePtr->Eqio_BaseAddress, XEQ_EQIO_ADDR_ISR);
}

