// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _iosc_controlOutLeds_HH_
#define _iosc_controlOutLeds_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct iosc_controlOutLeds : public sc_module {
    // Port declarations 7
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<4> > ctrl;
    sc_in< sc_lv<4> > inSwitch;
    sc_out< sc_lv<4> > outLeds;
    sc_out< sc_logic > outLeds_ap_vld;
    sc_in< sc_logic > internalPulse;


    // Module declarations
    iosc_controlOutLeds(sc_module_name name);
    SC_HAS_PROCESS(iosc_controlOutLeds);

    ~iosc_controlOutLeds();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<32> > v_assign_fu_106;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > internalLEDValue_fu_157_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<4> > val_V_read_fu_110_p2;
    sc_signal< sc_lv<1> > tmp_fu_148_p2;
    sc_signal< sc_lv<1> > tmp_1_read_fu_129_p2;
    sc_signal< sc_lv<4> > v_V_fu_141_p2;
    sc_signal< sc_lv<4> > v_V_1_fu_163_p1;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    sc_signal< bool > ap_condition_92;
    sc_signal< bool > ap_condition_40;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_9;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<4> ap_const_lv4_B;
    static const sc_lv<4> ap_const_lv4_C;
    static const sc_lv<4> ap_const_lv4_D;
    static const sc_lv<4> ap_const_lv4_E;
    static const sc_lv<4> ap_const_lv4_F;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_condition_40();
    void thread_ap_condition_92();
    void thread_internalLEDValue_fu_157_p2();
    void thread_outLeds();
    void thread_outLeds_ap_vld();
    void thread_tmp_1_read_fu_129_p2();
    void thread_tmp_fu_148_p2();
    void thread_v_V_1_fu_163_p1();
    void thread_v_V_fu_141_p2();
    void thread_val_V_read_fu_110_p2();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
