// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "iosc_controlOutLeds.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic iosc_controlOutLeds::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic iosc_controlOutLeds::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> iosc_controlOutLeds::ap_ST_fsm_state1 = "1";
const sc_lv<3> iosc_controlOutLeds::ap_ST_fsm_state2 = "10";
const sc_lv<3> iosc_controlOutLeds::ap_ST_fsm_state3 = "100";
const sc_lv<32> iosc_controlOutLeds::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> iosc_controlOutLeds::ap_const_lv32_1 = "1";
const sc_lv<32> iosc_controlOutLeds::ap_const_lv32_2 = "10";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_0 = "0000";
const sc_lv<1> iosc_controlOutLeds::ap_const_lv1_0 = "0";
const sc_lv<1> iosc_controlOutLeds::ap_const_lv1_1 = "1";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_1 = "1";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_2 = "10";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_3 = "11";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_4 = "100";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_5 = "101";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_6 = "110";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_7 = "111";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_8 = "1000";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_9 = "1001";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_A = "1010";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_B = "1011";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_C = "1100";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_D = "1101";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_E = "1110";
const sc_lv<4> iosc_controlOutLeds::ap_const_lv4_F = "1111";
const bool iosc_controlOutLeds::ap_const_boolean_1 = true;

iosc_controlOutLeds::iosc_controlOutLeds(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_condition_40);
    sensitive << ( val_V_read_fu_110_p2 );
    sensitive << ( tmp_fu_148_p2 );
    sensitive << ( tmp_1_read_fu_129_p2 );

    SC_METHOD(thread_ap_condition_92);
    sensitive << ( val_V_read_fu_110_p2 );

    SC_METHOD(thread_internalLEDValue_fu_157_p2);
    sensitive << ( v_assign_fu_106 );

    SC_METHOD(thread_outLeds);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( val_V_read_fu_110_p2 );
    sensitive << ( tmp_fu_148_p2 );
    sensitive << ( v_V_fu_141_p2 );
    sensitive << ( v_V_1_fu_163_p1 );
    sensitive << ( ap_condition_92 );
    sensitive << ( ap_condition_40 );

    SC_METHOD(thread_outLeds_ap_vld);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( val_V_read_fu_110_p2 );
    sensitive << ( tmp_fu_148_p2 );
    sensitive << ( tmp_1_read_fu_129_p2 );

    SC_METHOD(thread_tmp_1_read_fu_129_p2);
    sensitive << ( internalPulse );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( val_V_read_fu_110_p2 );
    sensitive << ( tmp_fu_148_p2 );

    SC_METHOD(thread_tmp_fu_148_p2);
    sensitive << ( inSwitch );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( val_V_read_fu_110_p2 );

    SC_METHOD(thread_v_V_1_fu_163_p1);
    sensitive << ( v_assign_fu_106 );

    SC_METHOD(thread_v_V_fu_141_p2);
    sensitive << ( ctrl );
    sensitive << ( inSwitch );

    SC_METHOD(thread_val_V_read_fu_110_p2);
    sensitive << ( ctrl );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );

    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "iosc_controlOutLeds_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ctrl, "(port)ctrl");
    sc_trace(mVcdFile, inSwitch, "(port)inSwitch");
    sc_trace(mVcdFile, outLeds, "(port)outLeds");
    sc_trace(mVcdFile, outLeds_ap_vld, "(port)outLeds_ap_vld");
    sc_trace(mVcdFile, internalPulse, "(port)internalPulse");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, v_assign_fu_106, "v_assign_fu_106");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, internalLEDValue_fu_157_p2, "internalLEDValue_fu_157_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, val_V_read_fu_110_p2, "val_V_read_fu_110_p2");
    sc_trace(mVcdFile, tmp_fu_148_p2, "tmp_fu_148_p2");
    sc_trace(mVcdFile, tmp_1_read_fu_129_p2, "tmp_1_read_fu_129_p2");
    sc_trace(mVcdFile, v_V_fu_141_p2, "v_V_fu_141_p2");
    sc_trace(mVcdFile, v_V_1_fu_163_p1, "v_V_1_fu_163_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_92, "ap_condition_92");
    sc_trace(mVcdFile, ap_condition_40, "ap_condition_40");
#endif

    }
}

iosc_controlOutLeds::~iosc_controlOutLeds() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void iosc_controlOutLeds::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_0) && 
         esl_seteq<1,1,1>(tmp_fu_148_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(tmp_1_read_fu_129_p2.read(), ap_const_lv1_1))) {
        v_assign_fu_106 = internalLEDValue_fu_157_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                 esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_0) && 
                 esl_seteq<1,1,1>(tmp_fu_148_p2.read(), ap_const_lv1_1)))) {
        v_assign_fu_106 = ap_const_lv32_0;
    }
}

void iosc_controlOutLeds::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void iosc_controlOutLeds::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void iosc_controlOutLeds::thread_ap_condition_40() {
    ap_condition_40 = (esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_0) && esl_seteq<1,1,1>(tmp_fu_148_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(tmp_1_read_fu_129_p2.read(), ap_const_lv1_1));
}

void iosc_controlOutLeds::thread_ap_condition_92() {
    ap_condition_92 = (esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_1) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_2) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_3) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_4) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_5) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_6) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_7) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_8) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_9) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_A) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_B) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_C) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_D) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_E) || esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_F));
}

void iosc_controlOutLeds::thread_internalLEDValue_fu_157_p2() {
    internalLEDValue_fu_157_p2 = (!ap_const_lv32_1.is_01() || !v_assign_fu_106.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(v_assign_fu_106.read()));
}

void iosc_controlOutLeds::thread_outLeds() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        if ((esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_0) && 
             esl_seteq<1,1,1>(tmp_fu_148_p2.read(), ap_const_lv1_1))) {
            outLeds = ap_const_lv4_0;
        } else if (esl_seteq<1,1,1>(ap_condition_40.read(), ap_const_boolean_1)) {
            outLeds = v_V_1_fu_163_p1.read();
        } else if (esl_seteq<1,1,1>(ap_condition_92.read(), ap_const_boolean_1)) {
            outLeds = v_V_fu_141_p2.read();
        } else {
            outLeds = "XXXX";
        }
    } else {
        outLeds = "XXXX";
    }
}

void iosc_controlOutLeds::thread_outLeds_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_0) && 
          esl_seteq<1,1,1>(tmp_fu_148_p2.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(tmp_1_read_fu_129_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_0) && 
          esl_seteq<1,1,1>(tmp_fu_148_p2.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
          (esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_1) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_2) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_3) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_4) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_5) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_6) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_7) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_8) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_9) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_A) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_B) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_C) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_D) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_E) || 
           esl_seteq<1,4,4>(val_V_read_fu_110_p2.read(), ap_const_lv4_F))))) {
        outLeds_ap_vld = ap_const_logic_1;
    } else {
        outLeds_ap_vld = ap_const_logic_0;
    }
}

void iosc_controlOutLeds::thread_tmp_1_read_fu_129_p2() {
    tmp_1_read_fu_129_p2 =  (sc_lv<1>) (internalPulse.read());
}

void iosc_controlOutLeds::thread_tmp_fu_148_p2() {
    tmp_fu_148_p2 = (!inSwitch.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(inSwitch.read() == ap_const_lv4_8);
}

void iosc_controlOutLeds::thread_v_V_1_fu_163_p1() {
    v_V_1_fu_163_p1 = v_assign_fu_106.read().range(4-1, 0);
}

void iosc_controlOutLeds::thread_v_V_fu_141_p2() {
    v_V_fu_141_p2 = (inSwitch.read() & ctrl.read());
}

void iosc_controlOutLeds::thread_val_V_read_fu_110_p2() {
    val_V_read_fu_110_p2 = ctrl.read();
}

void iosc_controlOutLeds::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

