// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _iosc_HH_
#define _iosc_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "iosc_pulse.h"
#include "iosc_controlOutLeds.h"

namespace ap_rtl {

struct iosc : public sc_module {
    // Port declarations 5
    sc_in_clk clk;
    sc_in< sc_logic > reset;
    sc_in< sc_lv<4> > ctrl;
    sc_in< sc_lv<4> > inSwitch;
    sc_out< sc_lv<4> > outLeds;


    // Module declarations
    iosc(sc_module_name name);
    SC_HAS_PROCESS(iosc);

    ~iosc();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    iosc_pulse* grp_iosc_pulse_fu_74;
    iosc_controlOutLeds* grp_iosc_controlOutLeds_fu_92;
    sc_signal< sc_lv<1> > iosc_ssdm_thread_s_load_fu_110_p1;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > grp_iosc_pulse_fu_74_internalPulse;
    sc_signal< sc_logic > grp_iosc_pulse_fu_74_internalPulse_ap_vld;
    sc_signal< sc_lv<4> > grp_iosc_controlOutLeds_fu_92_outLeds;
    sc_signal< sc_logic > grp_iosc_controlOutLeds_fu_92_outLeds_ap_vld;
    sc_signal< sc_logic > grp_iosc_controlOutLeds_fu_92_internalPulse;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > internalPulse;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_internalPulse();
    void thread_outLeds();
    void thread_ap_CS_fsm();
    void thread_ap_CS_fsm_state2();
    void thread_grp_iosc_controlOutLeds_fu_92_internalPulse();
    void thread_iosc_ssdm_thread_s_load_fu_110_p1();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
