webtalk_init -webtalk_dir D:\\Xilinx\\Assignment_2\\EmbeddedSystem_labs\\lab_7\\lab_7.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-10-03 16:17:38" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "5a34m2cd5blu6p6knfsi3v47gc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1538575097220" -context "sdk\\\\application/1538575097220"
webtalk_add_data -client sdk -key hwid -value "1538573090960" -context "sdk\\\\application/1538575097220"
webtalk_add_data -client sdk -key bspid -value "1538573430420" -context "sdk\\\\application/1538575097220"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1538575097220"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1538575097220"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1538575097220"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1538575097220"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1538575097220"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1538575097220"
webtalk_add_data -client sdk -key projSize -value "174.99609375" -context "sdk\\\\application/1538575097220"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1538576258796"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1538576258796"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1538576258796"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1538576258796"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1538576258796"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1538576258796"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1538576258796"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1538576258796"
webtalk_transmit -clientid 33090424 -regid "" -xml D:\\Xilinx\\Assignment_2\\EmbeddedSystem_labs\\lab_7\\lab_7.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Xilinx\\Assignment_2\\EmbeddedSystem_labs\\lab_7\\lab_7.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Xilinx\\Assignment_2\\EmbeddedSystem_labs\\lab_7\\lab_7.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
